version: "3.1"
services:
    keycloak:
        image: jboss/keycloak:latest
        restart: always
        ports:
            - 8080:8080
        environment:
            KEYCLOAK_PASSWORD: admin
            KEYCLOAK_USER: admin
        volumes:
            - ./.docker-volume/data:/opt/jboss/keycloak/standalone/data
            - ./src:/tmp/has-otp